#include "DHT.h"               // Necessary libraries
#include "Adafruit_BMP085.h"    
#include "ThingSpeak.h"
#include "WiFi.h"

#define pin1 13                  
#define pin2 32

const char* ssid ="ssid";          // Your local wifi name here
const char* password= "password";          // Password goes here

unsigned long channelID= channelID;       // ID from the auto-generated channel by ThingSpeak
const char* WriteAPIKey= "WriteAPIKey";             // API Key auto-generated by ThingSpeak

WiFiClient Client;   //Your WiFi client name

DHT dht1(pin1, DHT11);       // Sensor´s name


Adafruit_BMP085 bmp;     //BMP´s name

void setup() {
  Serial.begin(115200);                           //Connect to port 115200 through Arduino
  Serial.println("Connection Test: ");

  WiFi.begin(ssid, password);             
  while (WiFi.status() != WL_CONNECTED)           //It will connect to your local wifi, otherwise it will type (.) each half a second
  {
    delay(500);
    Serial.print(".");
  }

  Serial.println("Wifi connected");              // Confirmation to know if ThingSpeak has been connected sucessfully, it will start sending data through your client
  ThingSpeak.begin(Client);


  dht1.begin();                                   //Sensors will start working

}

void loop() {

  delay(2000);                                   // At this point, sensor would need to wait 2 seconds, just to start both Arduino´s terminal and ThingSpeak reciving the data
  leerdht1();

  ThingSpeak.writeFields(channelID, WriteAPIKey);
  Serial.println("Data sent to ThingSpeak");
  delay(14000);
}

void leerdht1() {

  float t1 = dht1.readTemperature();                                  //Control process for DHT sensors, with it´s assignated entities
  float h1 = dht1.readHumidity();

  while (isnan(t1) || isnan(h1)) {
    Serial.println("The readings from the DHT sensors are unavailable, retrying connection...");
    delay(2000);
    t1 = dht1.readTemperature();
    h1 = dht1.readHumidity();
  }

  Serial.print("DHT1 temperature: ");
  Serial.print(t1);
  Serial.println(" C ");

  Serial.print("DHT1 Humidity: ");
  Serial.print(h1);
  Serial.println(" % ");

  Serial.println("----------------");

  ThingSpeak.setField(1, t1);
  ThingSpeak.setField(2, h1);
}

/*
void leerdht2() {

  float t2 = dht2.readTemperature();
  float h2 = dht2.readHumidity();

  while (isnan(t2) || isnan(h2)) {
    Serial.println("Lectura fallida en el sensor DHT12, repitiendo la lectura...");
    delay(2000);
    t2 = dht1.readTemperature();
    h2 = dht1.readHumidity();
  }

  Serial.print("DHT2 temperature: ");
  Serial.print(t2);
  Serial.println(" C ");

  Serial.print("DHT2 humidity: ");
  Serial.print(h2);
  Serial.println(" % ");

  Serial.println("----------------");
}
*/

/*

void leerbmp() {

  float temp = bmp.readTemperature();
  float pres = bmp.readPressure();
  float altitude = bmp.readAltitude();
}

*/
